name: Sync to Hugging Face Hub

on:
  push:
    branches: [main]
    paths:
      - 'backend/**' 

  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face Spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          cd backend

          git init
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Auto deploy dari GitHub Actions"

          git push --force https://nupers:$HF_TOKEN@huggingface.co/spaces/nupers/gascopez master:main